//these are server file routes
let express = require('express')
let db = require('../models')
//let Customer = require('../models').Customer
//let Order = require('../models').Order
let Customer = db.Customer
let Orders = db.Orders
let Boxes = db.Boxes
let OrderItems = db.orderItems
//let queryInterface = require('Sequelize').QueryInterface

let router = express.Router()

//create a new customer w a post route to /customers; return status 201/ok if works
router.post('/customer', function(req, res, next) {
    Customer.create(req.body).then( (data) => {
        return res.json(data)
    }).catch( err => {
        console.log(err)
        if(err instanceof Sequelize.ValidationError) {
            let message = err.errors.map( (e) => e.message)
            return res.status(400).json(message)
        }
        return next (err)
    })
})


//a route to post a new box
router.post('/boxes', function(req, res, next) {
    Box.create(req.body)
    .then( (data) =>{
        return res.status(201).send('ok')
    
    })
})

router.get('/boxes', function(req, res, next) {
    Boxes.findAll()
    .then( boxes => {
        console.log('boxes here')
        return res.json(boxes)
    })
    .catch( err => next.err() )
})

//route to create a new order
router.post('/orders', function(req, res, next) {
    //order table needs customerID - other columns are autogenerated(orderID and datePlaced)
//this is sent from App.vue - order = {customerID: this.customerID, boxes: boxes, quantity also}
    let orderFromCustomer = {customerID: req.body.customerID}
    console.log('line 52 in api.js', req.body)
    //let boxes = req.body.boxes //original
    let boxesAndQuantities = req.body.boxesAndQuantities
    
    Orders.create(orderFromCustomer)
        .then( (orderFromDB) =>{
            //convert boxes into form expected by one OrderItem for in dbase
           // console.log('line 59', req.body)
            
            //let orderItems = boxes.map(function(box) {//original
                let orderItems = boxesAndQuantities.map(function(boxAndQuantities) {
                //return { order: orderFromDB.id, boxID: box.id}
                return { orderID: orderFromDB.id, boxID: box.id, quantity: box.quantity}
            })
            //console.log('line62', orderItems)
            OrderItems.bulkCreate(orderItems).then( () => {
             
                return res.send('inserted into order and orderItems')
            })

    })

})





module.exports = router